### ISSUE TITLE
Discord not detected on Linux when installed via flatpak, snap, etc.

### ISSUE THREAD

**Issue by ungive** [ungive/discord-music-presence#105]
Discord is not detected when installed with these package managers:
- Flatpak
- Snap
- ... more?

If you know about more package managers that sandbox Discord and/or don't expose the Discord RPC socket in the usual way, feel free to comment, outlining how you installed Discord!

If you know about a solution or you find any useful links, feel free to comment as well!

**Comment by gurneetsingh0** [comment]
try this if it helps https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

**Comment by ungive** [comment]
Fixed: https://github.com/ungive/discord-rpc/commit/144eff3c329d754a7a99c57f4965555ef0172cb8
