### ISSUE TITLE
(Elisa) My media player is not detected

### ISSUE THREAD

**Issue by VZCE** [ungive/discord-music-presence#114]
Players I am using, that aren't supported yet:
```
version: 2.2.7
lin_mpris: elisa - elisa (enabled)
signature: b7f715f0f820a90d
```

---

Note : Every metadata are well reported through playerctl. Well detected in MP, but nothing shows up on Discord.

**Comment by ungive** [comment]
https://apps.kde.org/de/elisa/

**Comment by ungive** [comment]
> Works for me

Actually stops working randomly because the `xesam:artUrl` is reported with a data string:

```
presence 2024-11-28T03:35:11.430Z INFO Discord: Presence updated: Schau mich nicht so an by Lotte on Glück via elisa (elisa) [2:36/3:15 playing] [cover:]
presence 2024-11-28T03:35:11.430Z DEBUG Discord: Cover image: data:image/png;base64,/9j/4AAQSkZJRgABAQECWAJYAAD/4gxYSUNDX1BST0ZJTEUAAQEAAAxITGlubwIQAAB...
...
presence 2024-11-28T03:34:42.759Z INFO Discord: Disconnected (1003): Unterminated string in JSON at position 16381 (line 1 column 16382)
```

That's a media detection bug:
- Data URLs need to be parsed and uploaded using the proxy server
- File URLs also need to be read into memory (if not too big) and upload using the proxy

**Comment by RileyIsPurple** [comment]
Not sure if this issue can be reopened, but MP still doesn't display Elisa's album cover to Discord.
I don't know any workarounds or solutions for this issue other than using a different player, but I would love to use Elisa instead.
I would love to see if this issue can be solved in anyway, as I prefer Elisa.

```
RileyIsPurple@RileysTabtop:~$ playerctl metadata
elisa mpris:artUrl              data:image/png;base64,/9j/4AAQSkZJRgABAQEASABIAAD/...
elisa mpris:length              198034000
elisa mpris:trackid             '/org/kde/elisa/playlist/1'
elisa xesam:album               this thought
elisa xesam:albumArtist         snuffles
elisa xesam:artist              snuffles
elisa xesam:title               this thought
elisa xesam:url                 file:///home/RileyIsPurple/Music/this thought - snuffles.mp3
```

**My system:**
- OS: Fedora Linux 44 (KDE Plasma Desktop Edition) x86_64
- Kernel: Linux 7.2.4-200.fc44.x86_64
- DE: KDE Plasma 6.7.5
- WM: KWin (Wayland)

**App versions:**
- Elisa 26.08.0
- Music Presense 2.3.6

**Comment by ungive** [comment]
@RileyIsPurple That's strange. Can you send the whole output? E.g. with `playerctl metadata > out.txt` and attaching `out.txt`.

Can you also attach your log file? It's located here: `~/.local/share/Music Presence/presence.log`

It works fine for me, my `mpris:artUrl` output starts with `elisa mpris:artUrl              data:image/png;base64,/9j/4AAQSkZJRgABAQEAYAB`, so so far it looks like yours isn't corrupted in any obvious way.

**Comment by RileyIsPurple** [comment]
@ungive Here's the text logs of both Music Presence and the full log of ``playerctl metadata``.
I'm unsure why no album covers pop up on Discord whatsoever, or if I have changed anything on my end to cause MP to break.
The album cover shows up on KDE's Miniplayer widget and Elisa itself.
- [playerctl.txt](https://github.com/user-attachments/files/32163715/playerctl.txt)
- [presence.log](https://github.com/user-attachments/files/32163714/presence.log)

**Comment by ungive** [comment]
You might be experiencing this bug here: https://github.com/ungive/discord-music-presence/issues/911

It will be fixed in the next release.

**Comment by RileyIsPurple** [comment]
@ungive How long until the next release comes out?
Or is there any workarounds I could do to fix this bug?

**Comment by ungive** [comment]
@RileyIsPurple You could try to disable IPv6 in your router or on your computer and see if that helps. You could also try to switch networks. If you use a VPN, you might want to try turning that off and see, if it helps.

The next release will be within a week, I hope. I'm adding Fluxer presence, I'm reworking the build pipeline and I'm fixing most open bugs (including the one I linked).

**Comment by RileyIsPurple** [comment]
@ungive I tried that and still no luck sadly. No album cover works unless it's an online radio station from Elisa (where the artURL is the image from the station and not a local file on the computer)

I'll just wait for the next release, thanks for the help :D
