### ISSUE TITLE
My media player is not detected

### ISSUE THREAD

**Issue by mafutofu12** [ungive/discord-music-presence#119]
Players I am using, that aren't supported yet:
```
version: 2.2.7
win_winrt: OperaSoftware.OperaWebBrowser.1717274660 - OperaSoftware.OperaWebBrowser.1717274660 (disabled)
win_winrt: harmonymusic.exe - harmonymusic (disabled)
signature: 43f06473963136ad
```

I want to display music being played on harmony music but it doesn't let me
---

**Comment by ungive** [comment]
Added Harmony Music: https://github.com/anandnet/Harmony-Music

It should be detected now :)

**Comment by mafutofu12** [comment]
thank you so much!
