### ISSUE TITLE
My media player is not detected

### ISSUE THREAD

**Issue by FamilyMink5** [ungive/discord-music-presence#120]
Players I am using, that aren't supported yet:
```
version: 2.2.7
win_winrt: Chrome - Chrome (disabled)
win_winrt: com.kakaoent.melon.player - com.kakaoent.melon.player (disabled)
signature: 6bb79c5dd349f891
```

---
Actually, I don't use this much, but since it's the most popular music service in Korea, I thought it would be nice to have it registered, so I posted this for now. Also, I have an image captured from msd.exe.
![스크린샷 2024-11-30 213706](https://github.com/user-attachments/assets/01d1a2be-9048-4d68-83c4-fcb63759a75c)
[Screenshot](<https://github.com/user-attachments/assets/01d1a2be-9048-4d68-83c4-fcb63759a75c>)
[Website](<https://www.melon.com/>)

**Comment by ungive** [comment]
Added, thank you for the detailed info!

Let me know if it works
