### ISSUE TITLE
Turn off App icon

### ISSUE THREAD

**Issue by githubyzer** [ungive/discord-music-presence#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Whenever I join a call on Discord, I always see the misplaced icon on the status. Besides, I think it is redundant when I already have "Listening to Apple Music" as a status.
![image](https://github.com/user-attachments/assets/26cc6190-0dcd-43a8-bcc0-1e1e51b0469e)

### Solution

Add an option for toggling app icon on/off.

**Comment by githubyzer** [comment]
I've seen the issue, and I've read the decision behind not adding this feature. Thanks for the heads up. I'll be switching back to the RP app I've been using as they have this option.

**Comment by githubyzer** [comment]
I really like the direction of this app tho. Please don't stop and keep updating. You already earned a star from me.

**Comment by ungive** [comment]
> I really like the direction of this app tho. Please don't stop and keep updating. You already earned a star from me.

I'm very glad you like it and there are many plans for new features! Stay tuned :)
