### ISSUE TITLE
(Moosync) My media player is not detected

### ISSUE THREAD

**Issue by VZCE** [ungive/discord-music-presence#126]
Players I am using, that aren't supported yet:
```
version: 2.2.7
win_winrt: Moosync.exe - Moosync (disabled)
signature: a6a49204b5cb3911
```

---

**Comment by ungive** [comment]
I'll add it when I release the next version tomorrow, which uses the [new players list](https://github.com/music-presence/media-players)!

**Comment by VZCE** [comment]
Sick ! 👍

**Comment by ungive** [comment]
Added!

Would you say this is a third-party client for Spotify/YouTube Music or more of an offline player that happens to integrate with those platforms? Would you also say "Listening to Spotify" or "Listening to YouTube Music" as alternatives to "Listening to Moosync" should be an option for this player?

**Comment by VZCE** [comment]
For a bit of context, Moosync is a music player that allows you to connect your YouTube, Spotify, SoundCloud, Tidal, Emby, Jellyfin, and Plex accounts, as well as access radio stations. Its main goal is to enable you to create playlists that combine content from all your services, offering a unified and extensive music catalog.

I think it wouldn’t make sense to display "Listening to Spotify" or "Listening to YouTube Music" as alternatives to "Listening to Moosync." Since Moosync allows playlists to include tracks from multiple platforms, music presence wouldn’t be able to accurately identify which service a given song is from. 👀

**Comment by ungive** [comment]
That makes a lot of sense, thanks!
