### ISSUE TITLE
Customizable track, artist, and album title prefixes

### ISSUE THREAD

**Issue by n0bodyyouknow** [ungive/discord-music-presence#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Currently there are appearance options to enable/disable a hard-coded artist prefix of "by" and an album prefix of "on".  It would be nice if these options were a text field where you could specify what prefix string you wanted to use.  Additionally, it would be nice to have this prefix option for the track title as well.

This would give more flexibility for using something like emojis (e.g. use "👤" for artist, "💿" for album, and "🎵" for track), or to support different languages.

### Solution

Change the artist and album prefix options under appearance to have a textbox where you can specify the prefix string.  These can be populated with the existing "by" and "on" strings respectively by default.
Add a matching track title prefix option.

**Comment by ungive** [comment]
Would #42 do what you're looking for? That will be added in the future.

I intend to keep the UI simple with "by" and "on" and maybe translations for it in the future, but custom format strings for the status should do what you've described!

**Comment by n0bodyyouknow** [comment]
Sorry, missed that issue.

Yes, supporting full customization of track title, artist, and album string formatting would certainly cover the functionality I've requested here!
