### ISSUE TITLE
[Bug] YouTube Music (Unofficial Client) playback time incorrect

### ISSUE THREAD

**Issue by zordem** [ungive/discord-music-presence#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Music presence doesn't seem to register when a song finishes and continues to count the playback time. This leads to the playback time being incorrect. This does not happen when manually skipping a song. I am not into deep in the matter so i can't say if this is a issue with music presence or the unofficial youtube music client.

### Reproduction Steps

1. Open the unofficial youtube music client and musci presence.
2. Play a song and wait till it ends.
3. After the song automatically changed, check the discord activity tab.

### Expected behavior

Playback time should reset to 00:00.

### Screenshots

![Discord_0zu00mx-14-12-2024-1734175329](https://github.com/user-attachments/assets/b20d3e97-1e21-4646-87fb-6e24125d9271)
![Discord_e6600my-14-12-2024-1734175337](https://github.com/user-attachments/assets/39bef478-8564-4670-85ff-18c49bcf8b21)

### Device Info

- Discord Music Presence version: 2.2.8
- Operating system: Windows
- The media player you used (if applicable): Unofficial YouTube Music Client (3.6.2.0)

**Comment by zordem** [comment]
Here are screenshots from the bahavior when manually skipping a song.

![Discord_o7O00mz-14-12-2024-1734176159](https://github.com/user-attachments/assets/b0ca17fe-3799-4fba-a6c2-854409dc3e50)
![Discord_tz600n0-14-12-2024-1734176169](https://github.com/user-attachments/assets/c65e4c7b-5cdb-4dd3-96a5-62d4c4b8e164)

**Comment by ungive** [comment]
I've tried it twice, once including the exact same songs you played, and I can't reproduce it.

The fact that it says 10:12 / 10:37 suggests to me that YouTube Music is showing wrong times. While Music Presence calculates the playback position dynamically, the duration is taken straight from YouTube Music and not modified.

You could run `msd.exe` from [here](https://github.com/ungive/media-session-dump/releases/tag/build2) to observe what YT Music reports when it happens again:

![image](https://github.com/user-attachments/assets/20870619-eaca-4209-b99c-6afadb2be65c)

**Comment by zordem** [comment]
I can't make much of the output of msd.exe. I've attached it.

![image](https://github.com/user-attachments/assets/ea126259-9fa5-4c4c-9af9-d34f45d405fc)

**Comment by ungive** [comment]
Thanks! The output shows that YouTube Music is in fact reporting those numbers, so it's not an issue with Music Presence.

`Position (live)` with a value of `429115ms` means that the playback position is at 7 minutes and 9 seconds (429115 milliseconds). The duration is 501928 milliseconds or 8 minutes and 21 seconds.

You could file an issue here: https://github.com/th-ch/youtube-music/issues
Make sure to reference this issue by linking to it! (`https://github.com/ungive/discord-music-presence/issues/131`)

If you don't know what to put in there, I can do it too, just lmk!

**Comment by zordem** [comment]
Hello again :D 

There was an update for th-ch/youtube-music released, two actually. I've read the changelogs and found [this pull request](https://github.com/th-ch/youtube-music/pull/2577). This seems to acknowledge the issue i have, but doesn't solve it. I'm not to deep into this topic and would greatly appreciate if you, with your expertise, would open an issue there.

**Comment by ungive** [comment]
Thanks for the update! Submitted an issue: https://github.com/th-ch/youtube-music/issues/2798
