### ISSUE TITLE
[Bug] Can't hide player music as "small_image"

### ISSUE THREAD

**Issue by LyKosDeluxe** [ungive/discord-music-presence#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i uncheck "Show player's logo" the logo still on my status
![image](https://github.com/user-attachments/assets/169c1547-bfdd-45e3-bf7e-0448b6b7ace7)
![image](https://github.com/user-attachments/assets/5fbe5372-5c24-4da7-bd92-dc10f95c03d2)

### Reproduction Steps

1. Interfaces/style/ appareance  (idk i use it in french)
2. uncheck "Show player's logo"
3. See the error

### Expected behavior

i expect to only be able to see "large_image" as album covert art 
and to remove the player logo

### Screenshots

![image](https://github.com/user-attachments/assets/169c1547-bfdd-45e3-bf7e-0448b6b7ace7)
![image](https://github.com/user-attachments/assets/5fbe5372-5c24-4da7-bd92-dc10f95c03d2)

### Device Info

- Discord Music Presence version: 2.2.8
- Operating system: Win10 22h2 19045.5247
- The media player you used (if applicable): Apple Music client for Windows

**Comment by ungive** [comment]
This is intended behaviour, see #46 and my more recent comment in #133
