### ISSUE TITLE
Murglar Request

### ISSUE THREAD

**Issue by Jaayymo** [ungive/discord-music-presence#138]
Hope it's not too much trouble, I'd like to see presence added for the media player Murglar, the source code is available [here](https://github.com/badmannersteam/murglar-downloads/releases) - appreciate your time!

**Comment by ungive** [comment]
Hey there, please follow the instructions under "If your media player is still not detected" to submit the required information so I can add this media player:

https://github.com/ungive/discord-music-presence/blob/master/documentation/troubleshooting.md#if-your-media-player-is-still-not-detected

**Comment by ungive** [comment]
Closing, see #139
