### ISSUE TITLE
Murglar submission issues

### ISSUE THREAD

**Issue by Jaayymo** [ungive/discord-music-presence#139]
Followed steps as asked, but I don't see any results similar to the other requests that show the version, signature etc. I want to be as helpful as possible, on install I had to update VLC media player so I feel like it works through this even though it doesn't have to be open to play my music.

**Comment by ungive** [comment]
If you followed [the instructions](https://github.com/ungive/discord-music-presence/blob/master/documentation/troubleshooting.md#if-your-media-player-is-still-not-detected) and there's no information in the issue that opens, then Murglar doesn't report what it is playing to the operating system. I suggest making a feature request with that media player, so they add it as a feature (imo every media player should have it), here's a template: https://github.com/ungive/discord-music-presence/blob/master/documentation/support-template.md
