### ISSUE TITLE
My media player is not detected (MPC-HC x86)

### ISSUE THREAD

**Issue by giggysmile** [ungive/discord-music-presence#140]
Players I am using, that aren't supported yet:
```
version: 2.2.8
win_winrt: CA9422711AE1A81C - CA9422711AE1A81C (disabled)
win_winrt: mpc-hc.exe - MPC-HC (disabled)
signature: df2c0591dc76f0cd
```

---
As requested, the x86 version (reported as `mpc-hc.exe`, no number). The SMTC setting is `View -> Options -> Player -> User Interface -> Windows Integration -> Control via Windows UI (SMTC)`

**Comment by ungive** [comment]
Thank you :) Added it!
