### ISSUE TITLE
Run on Startup Setting

### ISSUE THREAD

**Issue by dylanjkl** [ungive/discord-music-presence#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Whenever my PC is launched I want Discord Music Presence to start with it. Imagining I am a user with little to no technical experience I wouldn't understand how to use shell start up to add it to start up programs myself.

### Solution

Add a setting to enable the program to run on at startup, so that the program always runs in the background for the user - this would take another step into solidifying Discord Music Presence (DMP) as a one-click install and forget about software for increased userbility.

### Alternatives

Users can press Windows + R and type shell:startup to get to the startup folder and add the program as a shortcut there it automatically run on startup, but this is quite technical (involves having to search google for a solution) for the casual user and involves extra steps.

### Additional context

Maybe have it as an option in the installer (as most programs do) as to if you want the program to launch at startup, and then the settings window could be for disabling it/enabling it after installation.

**Comment by ungive** [comment]
Thanks for taking the time to suggest this! It's definitely on the list and I'll prioritise it a bit higher, so that hopefully this can be part of the next release.

**Comment by ungive** [comment]
With the next release Music Presence on Windows will automatically start at login, with the option to toggle this in the settings menu.

See [CHANGELOG](https://github.com/ungive/discord-music-presence/blob/master/CHANGELOG.md).
