### ISSUE TITLE
Pandora support

### ISSUE THREAD

**Issue by hg0428** [ungive/discord-music-presence#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I use Pandora and I want Discord rich presence for my music.

### Solution

I would like support for Pandora. Pandora has an app for pretty much every device. In addition, there is a sign-in-with Pandora capability that could be added to this system to potentially work with the browser.

**Comment by ungive** [comment]
Do you mean this? https://www.pandora.com

When I visit the site I unfortunately get: "Pandora is unavailable in this country or region" (I live in Germany).

Are you using a Desktop application for Pandora? If so, could you first play some media with Pandora while Music Presence is opened and then navigate to "Help > My media player is not detected"? That will open a new GitHub issue with information about the media players you have used with Music Presence so far, including Pandora, which will give me information that is needed to add support for it.

You can either just submit that issue or copy paste the text from it here.

> In addition, there is a sign-in-with Pandora capability that could be added to this system to potentially work with the browser.

For the desktop application (if it exists) Music Presence gets metadata from your operating system. If Pandora communicates what it's playing to the operating system, then something like "sign in with Pandora" won't be necessary.

For the browser: I am currently in the process of writing a browser extension which would accompany Music Presence in the future, to allow you to detect media that is playing in your browser and show it in your Discord status.

Generally. the idea is to keep the communication with media players minimal to non-existent. In it's current state Music Presence does not actively talk to any media player, but merely to the operating system to gather information. I'd like to keep it that way, so I likely won't implement something like "sign in with XYZ" in the future, but that shouldn't be necessary anyway if Pandora communicates what it's playing to the operating system properly (which it likely does).

**Comment by hg0428** [comment]
> Do you mean this? https://www.pandora.com
> 
> 
> 
> When I visit the site I unfortunately get: "Pandora is unavailable in this country or region" (I live in Germany).
> 
> 
> 
> Are you using a Desktop application for Pandora? If so, could you first play some media with Pandora while Music Presence is opened and then navigate to "Help > My media player is not detected"? That will open a new GitHub issue with information about the media players you have used with Music Presence so far, including Pandora, which will give me information that is needed to add support for it.
> 
> 
> 
> You can either just submit that issue or copy paste the text from it here.
> 
> 
> 
> > In addition, there is a sign-in-with Pandora capability that could be added to this system to potentially work with the browser.
> 
> 
> 
> For the desktop application (if it exists) Music Presence gets metadata from your operating system. If Pandora communicates what it's playing to the operating system, then something like "sign in with Pandora" won't be necessary.
> 
> 
> 
> For the browser: I am currently in the process of writing a browser extension which would accompany Music Presence in the future, to allow you to detect media that is playing in your browser and show it in your Discord status.
> 
> 
> 
> Generally. the idea is to keep the communication with media players minimal to non-existent. In it's current state Music Presence does not actively talk to any media player, but merely to the operating system to gather information. I'd like to keep it that way, so I likely won't implement something like "sign in with XYZ" in the future, but that shouldn't be necessary anyway if Pandora communicates what it's playing to the operating system properly (which it likely does).

Okay thanks, I'll make sure to try that and get the extra information.

**Comment by ungive** [comment]
Closing. If there is interest in Pandora support again, feel free to open another issue!
