### ISSUE TITLE
My media player is not detected

### ISSUE THREAD

**Issue by naufalkharits** [ungive/discord-music-presence#20]
Players I am using, that aren't supported yet:
```
win_winrt: AppleInc.AppleMusicWin_nzyj5cx40ttqa!App - AppleInc.AppleMusicWin_nzyj5cx40ttqa!App (disabled)
win_winrt: Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic - Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic (disabled)
signature: 238418a17ce4d6ad
```

---
**Media Player (by Microsoft) and Apple Music (Windows 11) weren't detected.**

**Comment by ungive** [comment]
I've added the identifier you submitted for Apple Music, so Apple Music should be detected for you, after you restart Music Presence (see [here](https://github.com/ungive/live.musicpresence.app/commit/775f740d2bb6102b8743f49dc41c5d4681bb2f6b)).

I previously decided to not support the Windows Media Player because it could contain media other than music (like a home video that may contain personal data), which I don't want to enable by default. I only want to enable pure music players by default.

That being said, I will add support for the Windows Media Player with the next release nevertheless, but it will be disabled by default, leaving the user the option to enable it by hand, if desired.

@naufalkharits Let me know if Apple Music works for you now!

**Comment by naufalkharits** [comment]
It won't detect Discord now

**Comment by ungive** [comment]
It should connect after at most ~30 seconds. Perhaps restart Discord. Make sure you are using the Discord desktop app (I assume you are). Also make sure that Music Presence is only opened once, not multiple times.

**Comment by naufalkharits** [comment]
restarted my PC, it detected both Discord and Apple Music.
But, shows `waiting for media playback`.

![image](https://github.com/ungive/discord-music-presence/assets/80172679/a27ad8c8-dce7-46b1-80ed-ff89ca8b29cd)

**Comment by naufalkharits** [comment]
played a song from Apple Music (bought from iTunes), I think it downloads automatically, so yah I guess it's on offline mode.
I'll check the logs.

**Comment by naufalkharits** [comment]
you're right.

> music-presence 2024-06-03T16:29:46.931Z INFO Skipping media from player AppleInc.AppleMusicWin_nzyj5cx40ttqa!App (AppleInc.AppleMusicWin_nzyj5cx40ttqa!App): Title "Kataomoi - From THE FIRST TAKE" is missing an artist

**Comment by ungive** [comment]
Figured.

I wasn't able to test Apple Music because I don't have a subscription, but it seems odd to me that downloaded music from iTunes doesn't have proper song metadata. From my testing with local files (mp3) that hat proper metadata it worked just fine, so Apple Music itself is reporting it correctly, but your song files/downloads must have an empty "Artist" tag field.

Generally speaking, one might argue Music Presence shouldn't skip media that doesn't have an artist and just show it in the status anyway. I've disabled it before because I'm not able to reliably search for song metadata online with just a title, so I decided to just disable it. I might as well enable it again. Might do that in the next release.

**Comment by naufalkharits** [comment]
have tried several things but won't work, weird tho the file has fully metadata.
I guess I just wait to next releases.

lemme know if I could help something.

**Comment by ungive** [comment]
You could show me what the media overlay looks like in Windows 10:

![grafik](https://github.com/ungive/discord-music-presence/assets/24623262/8e968363-bfa7-4a86-a4f3-2651d1b99b3f)

If you're on Windows 11 that information should be located here:

![grafik](https://github.com/ungive/discord-music-presence/assets/24623262/4f48068e-19cb-40d0-8597-379d8e074d7a)

If there's no separation between title and artist Apple Music just reports it wrong.

**Comment by naufalkharits** [comment]
after cleanup my Apple Music (previously still mixed with the old iTunes folder, since Apple migrated from old iTunes to new Apple Music app), Windows 11 Media Player couln't detect the artwork now 😂
![image](https://github.com/ungive/discord-music-presence/assets/80172679/37db574a-ebd8-4cd9-978a-a22cf46af2cc)

Artwork files in directory `Apple Music > Apple Music Library.musiclibrary` and music files in directory `Apple Music > Media > Music`
![image](https://github.com/ungive/discord-music-presence/assets/80172679/e755fc34-f6a3-4d3e-b02f-3b7ff39dcad2)

tho the media overlay looks normal same like what you sent.
![image](https://github.com/ungive/discord-music-presence/assets/80172679/d8957838-669d-47ff-8235-622a1626efe0)

**Comment by ungive** [comment]
And the logs still say that the media you are currently playing is missing an artist?

**Comment by naufalkharits** [comment]
yes

> music-presence 2024-06-04T03:41:21.554Z INFO No media players detected
music-presence 2024-06-04T03:45:59.589Z INFO Skipping media from player AppleInc.AppleMusicWin_nzyj5cx40ttqa!App (AppleInc.AppleMusicWin_nzyj5cx40ttqa!App): Title "A Million Dreams" is missing an artist
music-presence 2024-06-04T03:47:37.451Z INFO No media players detected
music-presence 2024-06-04T03:47:37.812Z INFO No media players detected
music-presence 2024-06-04T04:04:04.625Z INFO Discord: Disconnected (1): Pipe closed

**Comment by ungive** [comment]
I've tried it myself with a local MP3 file and it's not working anymore here either:

> music-presence 2024-06-04T16:43:21.367Z INFO Skipping media from player Apple Music (AppleMusic.exe): Title "Ava" is missing an artist

The metadata of the mp3 file I am playing is complete (it has title and artist):

![grafik](https://github.com/ungive/discord-music-presence/assets/24623262/d29dfb4f-073c-4527-abf9-d8feab7bfb99)

It worked before with the very same file (I haven't changed it).

If I look at the raw data from Windows it's apparent that Apple Music does not report any artist (or Windows drops the data along the way somewhere):

![grafik](https://github.com/ungive/discord-music-presence/assets/24623262/25ba67f1-3ee0-4517-8e23-5735f18dcf82)

Yet it looks just fine with the media controls:

![grafik](https://github.com/ungive/discord-music-presence/assets/24623262/fe1014d6-bd20-48a3-a9df-55900b53c5c7)

I haven't updated Apple Music and I've also tried it with older builds of Music Presence (previous version), to no avail.

---

Some more digging revealed that it's setting the "album artist" now and apparently completely omits the "artist" (?):

![grafik](https://github.com/ungive/discord-music-presence/assets/24623262/0b3649ad-1560-4bd9-ab82-15aa827cc2b1)

The data is just completely wrong now, the album artist contains the "album + artist" as a single string, even though it's meant to contain the artist of the album (see https://mkoby.com/2007/02/18/artist-versus-album-artist/).

Someone messed up at Apple it seems..

There's nothing I can do about that unfortunately. I'll see if I can report this to Apple somehow, but their application is at fault here..

**Comment by ungive** [comment]
I don't have an Apple ID and I don't intend to create one just to report this issue.

@naufalkharits You (or any other Apple user here) can consider reporting this issue to Apple by creating a bug report here: https://developer.apple.com/bug-reporting/

Here's my explanation of the issue, so you won't have to write it yourself. You can just copy paste it:

> I am contacting you on behalf of an application/software developer which has experienced issue when interfacing with Apple Music for Windows through Windows system APIs. This is his explanation of the issue:
>
> Apple Music for Windows reports music metadata (title, artist, album, playback position, etc.) to the operating system, so that other applications can see what the Apple Music media player is currently playing. I am using a low-level C++ API, called WinRT, to access that information. When I attempt to read the artist name it reports no information at all. This has worked before (a few weeks ago). Also, when I look at the "album artist" it reports e.g. "Famy - Ava" which is a combination of the album name ("Ava") and the artist name ("Famy"). This is malformed information, it should only report the artist name who worked on the album and not some combination of multiple fields.
>
> The following low-level C++ functions (of the WinRT API) are used to retrieve this information:
Artist: Windows.Media.Control.GlobalSystemMediaTransportControlsSessionMediaProperties.Artist()
AlbumArtist: Windows.Media.Control.GlobalSystemMediaTransportControlsSessionMediaProperties.AlbumArtist()
Documentation: https://learn.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssessionmediaproperties?view=winrt-22621
>
> The return value of Artist() is empty (null). The return value of AlbumArtist() is a combination of the artist and the album name. The purpose of the WinRT is to be able to access the artist and album separately, not combined in a single string. The album artist is supposed to only contain the name of the artist and nothing else.
>
> This is a bug that should be fixed, so that other applications are able to detect what media is played in the Apple Music media player.
>
> Thank you.

Let me know if you had the time to report it to Apple!

I'll close this issue, as this is not an issue with Music Presence anymore.

**Comment by naufalkharits** [comment]
thanks for the explanation, I've reported it to Apple.
but unfortunately I didn't find a category for the Windows platform (as expected tho, Apple users on other platforms are always lower class citizens), but let's see if this can find some light.

**Comment by naufalkharits** [comment]
v2.1.2 fixed the issue
![image](https://github.com/ungive/discord-music-presence/assets/80172679/95244061-cbcf-407d-8441-f8cde82dbc0f)
tho the artwork is still missing accurated.
![image](https://github.com/ungive/discord-music-presence/assets/80172679/98a25f34-0deb-49ac-94b9-813a0aa74dcf)
![image](https://github.com/ungive/discord-music-presence/assets/80172679/1788b114-c599-4d2e-8115-85c6c3d9c614)

**Comment by ungive** [comment]
This is expected, as an external service (MusicBrainz) is used to retrieve the album cover for the song that you're currently playing, It doesn't have all songs available and sometimes doesn't find the right song, if the song name or artist contains unexpected things like "feat. xyz" or "(Acoustic Version)".

A solution for that is being tracked in #27.
