### ISSUE TITLE
Link to multiple streaming platforms

### ISSUE THREAD

**Issue by probablyzal** [ungive/discord-music-presence#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

When you click the "Listen to this song" from the Discord presence, add a link to different streaming platforms where the song/album is available. Sort of like Songwhip. 
![links](https://github.com/ungive/discord-music-presence/assets/171434233/6ddd80ff-cb8d-404a-bf28-45e44362ca25)

**Comment by ungive** [comment]
For players other than TIDAL this is definitely a good enhancement.

With Songwhip it appears that it's not possible to get a link to a song programmatically without knowing the URL to one of the music streaming platforms, which is information that is not available to me when detecting media on the Desktop. 

https://songwhip.com/faq#does-songwhip-have-an-api

> There's a simple API that will return a Songwhip page URL (and some metadata) given a 'source' music URL (Spotify, Apple Music, YouTube, etc).
`curl --request POST --data '{"url":"MY_SOURCE_MUSIC_LINK"}' https://songwhip.com/`
The API payload doesn't include the final music service links as we want to encourage people to use the Songwhip platform.

If anyone knows more platforms to get song links, feel free to mention them here and I'll see which one might be best suited.

Platforms to get song links I currently know of:

- https://odesli.co/

**Comment by ungive** [comment]
If you're reading this, you can help by looking for services/APIs that offer programmatic retrieval of song links for specific platforms (like Spotify or Apple Music) or that offer a URL to a service which has links to other platforms (like Odesli and Songwhip).

The requirements are that it must be possible to search with **song title** and **artist**, and optionally the **album name**. Searching with a platform URL (which is how Songwhip works) will be insufficient, as most of the time that won't be available.

Thanks for the help!

I will come back to this later, once more important and urgent features have been implemented.

**Comment by ungive** [comment]
Right now this is not a priority, as it is more of a "nice to have" feature and I am focusing on other features, see [the project roadmap](https://github.com/ungive/discord-music-presence/blob/master/documentation/roadmap.md). I will give this issue the "future" label and I will come back to it once I find the time for it!
