### ISSUE TITLE
My media player is not detected

### ISSUE THREAD

**Issue by Jqro1** [ungive/discord-music-presence#23]
Players I am using, that aren't supported yet:
```
win_winrt: firefox.exe - Firefox (disabled)
signature: b0a750a9e0ec511d
```

---

**Comment by ungive** [comment]
I'm currently working on adding support for browsers, see this issue: #5 

In one of the next releases (not too far in the future), you will be able to install a browser extension that will communicate with Music Presence to show browser media in your Discord status.

I hope that is what you are looking for. Stay tuned!

**Comment by ungive** [comment]
If you were trying to ask for support of a media player other than Firefox, please play some music/media with that player first while Music Presence is opened and then click "My media player is not detected" and submit the issue again. That way I will get info about that media player.

Closing this issue.
