### ISSUE TITLE
Use Listening activity type instead of Playing type

### ISSUE THREAD

**Issue by n1ckoates** [ungive/discord-music-presence#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Currently, Music Presence uses the "Playing" status (activity type `0`), which is not the ideal way to show that you're listening to music. Spotify's Discord integration, for example, says "Listening to Spotify" instead.

### Solution

Music Presence should switch to the "Listening" status ([activity type `2`](https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-types)).

### Alternatives

There are other supported activity types ("Playing", "Watching", and "Competing in") that are available, but they don't make sense for music. Still, users might want to keep "Playing," so it could be worth adding an option to customize this.

### Additional context

[Discord just added support for this](https://x.com/advaithj1/status/1816655583107510517), which wasn't previously possible.

**Comment by n1ckoates** [comment]
Yes, I'm certain the information is accurate - it's from a Discord employee. I was able to set the status to Listening with a TIDAL client mod: https://github.com/Inrixia/neptune-plugins/pull/37

Most libraries don't support it yet, because changing the activity type was previously unsupported.

**Comment by ungive** [comment]
Thanks for the pointers.

I digged into [discord-rpc](https://github.com/discord/discord-rpc) a bit more and implementing the change was trivial:

![grafik](https://github.com/user-attachments/assets/72f25db4-57f1-434c-8880-e982f6087bbb)

It seems though that timestamps are not shown. I'll see what I can do about that.

I'll try make a release for this this weekend.

**Comment by ungive** [comment]
Seems it's not possible to get the timestamps with the listening type, if the docs can be taken literally (emphasis mine):

> timestamps? Unix timestamps for start and/or end of the **game**

https://discord.com/developers/docs/topics/gateway-events#activity-object

A bit unfortunate in my opinion. I don't use X, but maybe you can reach out to the intern who implemented the change and bring to his attention that timestamps would make sense on the listening activity type too, in case you're of that opinion as well.

**Comment by n1ckoates** [comment]
Already reached out with that feedback, they said they'll probably change it.

**Comment by ungive** [comment]
Would be awesome if it looked the same as the Spotify status, with an actual progress bar. :)

**Comment by ungive** [comment]
Implemented as part of the [v2.1.3 release](https://github.com/ungive/discord-music-presence/releases/tag/v2.1.3).

**Comment by degu-Tanya** [comment]
> Would be awesome if it looked the same as the Spotify status, with an actual progress bar. :)

I saw this on vencord, but I guess its only for macOS with the apple music app. (or else I bet they would have done it for windows + apple music app)
I would really love for this to be possible for all music apps and systems one day (discord please allow it)
https://github.com/Vendicated/Vencord/tree/main/src/plugins/appleMusic.desktop
![335073274-1f811090-ab5f-4060-a9ee-d0ac44a1d3c0](https://github.com/user-attachments/assets/308859bb-346c-4140-8803-bbc432f07659)

**Comment by ungive** [comment]
@degu-Tanya Do you know if it looks like this to non-Vencord users as well? I've never seen a progress bar like this for anything but Spotify. It might be a visual enhancement added by Vencord itself.

Feel free to join the [Discord server](https://discord-invite.musicpresence.app/), would love to see it!

**Comment by degu-Tanya** [comment]
I sadly do not have macOS, I asked in the vencord discord server and and a user with coding role said everyone can see it. but I tried to see if anyone on the server list used it but I failed to see anyone with the plugin and apple music playing.
