### ISSUE TITLE
Basic WebSocket Server That Reports Currently Playing Music

### ISSUE THREAD

**Issue by AlanMoonbase** [ungive/discord-music-presence#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Currently Music Presence is only reporting music information to Discord. I want to be able to report realtime music information to other applications that support WebSockets.

### Solution

A basic WebSocket Listener that constantly reports currently playing music over a localhost address.

### Alternatives

As far as I know there is no alternative apps that do this, feel free to correct me if I'm wrong.

### Additional context

I play a social vr game called Resonite which has a built in WebSocket Client for doing whatever you want with. This could also be useful for other games like VRChat.

**Comment by ungive** [comment]
Hey there, thank you for your suggestion.

I am planning to add integrations with other platforms in the future, but at this moment exposing playback information through a Websocket from within Music Presence is not on the roadmap. I assume you only play Resonite on Windows, implementing a simple Websocket server with e.g. Python and using WinRT to get playback information should be pretty straightforward: https://stackoverflow.com/a/66037406/6748004

Adding Websockets to Music Presence would be another component to maintain and I want to focus on other features right now, see the [roadmap](https://github.com/ungive/discord-music-presence/blob/master/ROADMAP.md).

Once I work on integrations with other platforms I will take this into consideration though.

**Comment by AlanMoonbase** [comment]
I will take this into consideration. Thank You!

**Comment by ungive** [comment]
Actually updated the [roadmap](https://github.com/ungive/discord-music-presence/blob/master/ROADMAP.md) this time, if you looked at it, you saw the old version before. :)
