### ISSUE TITLE
[Bug] Settings not saved on exit

### ISSUE THREAD

**Issue by PapitaConPure** [ungive/discord-music-presence#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Settings aren't being saved after closing the program for the first time. I can't edit the settings.json file because I don't have 
write permissions for it.

### Reproduction Steps

1. Start Music Presence
2. Tick the 'Show the song title and artist on separate lines' checkbox
3. Click 'Exit'
4. Start Music Presence again
5. See the error - change wasn't saved

### Expected behavior

I expect settings to be saved after I close the program.

### Screenshots

https://github.com/user-attachments/assets/c7c7025e-375d-4e0f-8f22-e9ccc9d888f7

### Device Info

- Discord Music Presence version: 2.1.3
- Operating system: Windows 10
- The media player you used (if applicable): n/a

### Additional context

I am the main and only user of the computer.

My Windows username has a tilde, "Papita con Pur**é**". I believe this might be related to the write permission issue, which could be causing this problem (I'm not sure though). The settings.json and stat.json files are saved here:
![image](https://github.com/user-attachments/assets/b9a49bc2-3de9-4dd4-b505-704afe00d7ed)

Notice how the last modification date ("fecha de modificación") of these two files is many hours behind the date of the video submitted above (08/30/2024 14:12):
![image](https://github.com/user-attachments/assets/6e6a261f-c9d0-4faf-9cd1-c873ff90f3f2)

**Comment by ungive** [comment]
Hey, thanks for reporting. Is there no presence.log file? It should exist, as well as some other files, but that's probably related to your username containing these characters which seem to cause the issue. If you can find any presence.log file, please share it, it might contain valuable error messages.

Are there any other files in the folder that you marked with a red box? Or only AppData\Roaming\Music Presence? If there are other files too other programs might have issues with it as well, if not, then it's likely just an issue with Music Presence.

**Comment by PapitaConPure** [comment]
Thank you for the fast response.

Unfortunately, I couldn't find a presence.log file anywhere. I also used Windows Search but didn't find anything either.

There are also these two folders with some files in them, inside the user folder with the correct name:
![image](https://github.com/user-attachments/assets/89e66d10-0d2b-4ab6-857e-e80d27a42551)

As for other programs inside the "incorrect" user folder, there's [PureRef](https://www.pureref.com) crash data inside AppData/Local/, but that program never had any issues for me. There's nothing else.

**Comment by PapitaConPure** [comment]
For now, I was able to save some settings after opening the file with VSCode and saving it as a superuser
![image](https://github.com/user-attachments/assets/e44cbe4d-05c0-4424-bbff-d1e14578d115)

**Comment by PapitaConPure** [comment]
After looking into it a bit more, I was able to manually enable the write permissions.
![image](https://github.com/user-attachments/assets/8d67e9b4-9018-4da4-a580-c2ee644f8cd4)

It's weird that I had to do that in the first place though. If you need more information, I'll be here.

**Comment by ungive** [comment]
I can reproduce this, where it doesn't write the settings or other files at all. But I don't get a strange folder name like that. I'll investigate further! Thanks for the detailed information.

**Comment by ungive** [comment]
I was converting between strings and wide strings, which messed up the encoding. Using the proper types now and it's fixed.

You reported this at the perfect time, I'm about to release version 2.2.0, so the fix will be part of that release!

While I was reproducing this I also encountered another important bug that I fixed, thanks for that!

You can expect the release for version 2.2.0 either tomorrow or on sunday.

**Comment by ungive** [comment]
@PapitaConPure Version 2.2.0 is here now, although released a little bit later. :)

**Comment by PapitaConPure** [comment]
Nice! Thank you for your hard work

**Comment by PapitaConPure** [comment]
Can confirm it's fixed now!
![image](https://github.com/user-attachments/assets/90222682-643c-4d33-8d65-ae3364422606)
