### ISSUE TITLE
Adding support for AIMP

### ISSUE THREAD

**Issue by naturbrilian** [ungive/discord-music-presence#37]
Players I am using, that aren't supported yet:
```
win_winrt: AIMP.exe - AIMP (disabled)
signature: fb160c30d625a2a9
```

I think it would be nice to add support for this player, considering that it also supports Media Control.

*The media control plugin is on the official site
---

**Comment by ungive** [comment]
Added AIMP, thanks for reporting!

Unfortunately it does not report accurate playback information, so you won't see the progress bar with timestamps as you can with other music players. That's most likely an issue with the AIMP plugin: http://www.aimp.ru/forum/index.php?topic=63341

If you are using a different plugin please let me know!

![image](https://github.com/user-attachments/assets/ec329518-88d6-4784-8e70-738c067c691e)

**Comment by Dryonefx01** [comment]
La integracion de la libreria pyaimp puede proporcionar esa informacion con mucha precisión con aimp.get_player_position()
<img width="689" height="363" alt="Image" src="https://github.com/user-attachments/assets/064efbf8-bb78-4dc9-9b2e-05c8d3bd7a54" />

**Comment by ungive** [comment]
> La integracion de la libreria pyaimp puede proporcionar esa informacion con mucha precisión con aimp.get_player_position()

I suppose you are talking about AIMP plugins? For support with Music Presence specifically, AIMP must report that information to Windows via [SMTC](https://learn.microsoft.com/en-us/windows/apps/develop/media-playback/integrate-with-systemmediatransportcontrols).

**Comment by Dryonefx01** [comment]
I really don't know if it could be called a plugin. [pyaimp](https://epocdotfr.github.io/pyaimp/) I know that with that python library you can make aimp dump the playback information without having to install any plugin, I just wanted to contribute that for music presence have integration with aimp. (sorry, my english is half broken)

**Comment by ungive** [comment]
> I really don't know if it could be called a plugin. [pyaimp](https://epocdotfr.github.io/pyaimp/) I know that with that python library you can make aimp dump the playback information without having to install any plugin, I just wanted to contribute that for music presence have integration with aimp. (sorry, my english is half broken)

Thank you, I've added it to this issue: https://github.com/ungive/discord-music-presence/issues/494

I will work on it in the future to support more media players that don't report some or any information!
