### ISSUE TITLE
Support for media players

### ISSUE THREAD

**Issue by ungive** [ungive/discord-music-presence#4]
### Overview

Currently the application detects almost all media players the user's system. Still, Music Presence only works with a small set of whitelisted applications. This is done for the following reasons:

- Generally speaking, I want to make sure that Music Presence works seamlessly with each media player. Before I add support for another media player, I want to make sure everything works smoothly. I can guarantee this best by focusing on one application at a time and testing extensively.
- Each media player needs an icon, so you can identify it in the tray menu. This icon needs to be created and added to the application, so that the application looks visually appealing.
- By completely disabling media players, the user is encouraged to inform me that they would like support for a specific media player. This is a good thing for me, as the developer of this application, as I get information from users for media players that I have never used before, like the executable name of the application and some platform-specific information.

The goal of handling it this way is, that Music Presence will hopefully accumulate well-developed support for all major media players over time, once enough users have suggested their favourite media player(s).

### Requesting support for a media player

Please follow these steps to request support for a media player or streaming service:

1. Try and play some music with the media player you want support for. This step is necessary.
2. Navigate to the **Help** menu and click on "**My media player is not detected**". This will open a tab in your browser with a new GitHub issue that has some information about your media players in it.
3. Review the contents of the issue and describe which media player/music player/streaming service you would like to use with Music Presence. Then click on the submit button.
4. I will look at it and come back to you as soon as I can.

What exactly happens when you do this?

- When you play music with a media player while Music Presence is running, the following information will be collected:
  - The name of the media player (e.g. "Spotify")
  - The operating on which you are using the media player (Windows, Mac or Linux)
  - A unique, platform-specific identifier for the application, usually the executable name (like "Spotify.exe")
- This information is not sent anywhere without your consent. By clicking on "**My media player is not detected**" in the help menu you open a new GitHub issue and you can review the information. Only by clicking on "Submit new issue", you will make your information public (to me and everyone else).

### How long does it take until support is added

Music Presence downloads information about supported media players on application startup. Once I have prepared everything, you simply need to restart the application! I'll get back to you once I added support for your media player in the issue you opened. You should be notified by e-mail as well (in case you have subscribed to the issue).

### What kind of media players will be supported?

There are a few criteria for media players to be supported:

- The media player must be a desktop application.
- The media player must be a player specifically for music and not a multimedia player, like a browser or VLC media player. In any other case, multimedia players won't get support and will never be enabled by default because media like videos are not intended to be shown in the Discord status by Music Presence. Picture this: You have Music Presence running in the background and you watch your favourite YouTube video and you forget that it's shown in your Discord status, even though you might not want that.

I know that media from browsers is something that might be wanted by users. Please read [this issue](https://github.com/jonasberge/discord-music-presence/issues/5) for more information on browser support.

**Comment by LiMoon** [comment]
hi, can add Windows Apple iTunes support?

**Comment by ungive** [comment]
> hi, can add Windows Apple iTunes support?

Can you run Music Presence, then play some music with iTunes and click on "Submit detected media players" in the "Help" menu of Music Presence?

That should open a new issue with information I need to add support for iTunes. Thanks!

**Comment by ungive** [comment]
All of the popular media players are supported now and it's pretty straightforward how to request support for another one. Closing.

**Comment by LiMoon** [comment]
Thank you. I followed the instructions and it works fine now.
