### ISSUE TITLE
Pause handling & new possible configuration option

### ISSUE THREAD

**Issue by NocFA** [ungive/discord-music-presence#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

At present once a track is paused, the rich presence disappears from your profile immediately.

### Solution

The first portion of this suggestion is to make this not happen, it'd be nice if the rich presence remained even when the track is paused, only dismissing it upon application closure (media player)

Secondly, this goes with the above; instead of showing the player on the small image, show a play/pause icon depending on the state regarding the above, scrobbler can remain, just, static until resume state, it seemingly already handles keeping its place upon resuming.; it'd

### Alternatives

It may be worth adding the option to switch between static player icon & play/pause icons, when the player option is selected, maybe revert to old behaviour, as, some people might like the way it is now.

**Comment by ungive** [comment]
> scrobbler can remain, just, static until resume state, it seemingly already handles keeping its place upon resuming.; it'd

What do you mean by that? Do you mean scrobbling to LastFM? Music Presence does not do any scrobbling at this time.

> The first portion of this suggestion is to make this not happen, it'd be nice if the rich presence remained even when the track is paused, only dismissing it upon application closure (media player)

That's definitely possible. I could add an option "leave status active until the player is closed" (or presence is deactivated).

> instead of showing the player on the small image, show a play/pause icon depending on the state regarding the above

I intend to always show the player icons for streaming services at the moment. As for offline media players, I could theoretically add the option to show playing/paused icons. I assume you're coming from the LastFM Discord integration which has that feature?

I'll put this together with another feature that was requested in the Discord, which is to allow for using "format strings" to customize the text that is shown (e.g. "{artist} - {title}"). I could allow to set the small image to a custom URL.

I'll open another issue for that.

**Comment by NocFA** [comment]
> What do you mean by that? Do you mean scrobbling to LastFM? Music Presence does not do any scrobbling at this time.

Ah, apologies, the word scrobble has a different meaning to me, as, I am a LastFM user :P
By scrobbler, I meant the playback duration handler, which, Discord has finally started showing when "listening to" is being used!
So, to clarify, that specific playback duration bar, when the player is paused, can simply pause, I would think.

As for the rest, that sounds reasonable to always show the player, however, it would be nice to instead have play & pause icons as a choice, I understand that it's not up to me, appreciate the work you've done, I shall be sponsoring this project soon, just trial running it and it seems like a major successor to all the prior implements of non-agnostic playback rich presence handlers.

**Comment by ungive** [comment]
> By scrobbler, I meant the playback duration handler, which, Discord has finally started showing when "listening to" is being used!

Ahh, thanks for clarifying!

> So, to clarify, that specific playback duration bar, when the player is paused, can simply pause, I would think.

I'm afraid that can't realistically be done as the timestamps that are used are "absolute" in time (start time is e.g. 20:13:45 o'clock, end time is 20:15:59 o'clock) which is then used by discord to determine the current progress bar offset. One would have to update the status every second for the progress bar to be "stuck in time" or fixed at a specific position. While that *might* work, it would probably be jumping around by a second at best + the status may only be updated 5 times per 20 seconds, which makes this infeasible. Would be awesome though if that was possible!

If I'd add the option to use format strings as in the example I gave, then one could show "Paused" on the third line e.g. if the player is paused (in place of the album).

> it would be nice to instead have play & pause icons as a choice

I'll keep that in mind when I add format strings!

> appreciate the work you've done, I shall be sponsoring this project soon, just trial running it and it seems like a major successor to all the prior implements of non-agnostic playback rich presence handlers.

Thank you! I really appreciate that :) My goal is to make Music Presence the de-facto replacement for all those half-baked rich presence implementations, which work but usually aren't very feature-complete or require additional steps to work.

**Comment by ungive** [comment]
@NocFA Implemented the changes, please let me know your thoughts before I publish them!

The tray icon will also reflect when the status is showing paused media.

> *Note: This feature will only be available for **offline music players** for now. I always want to show the brand of the streaming service if a streaming service is playing the media, to make sure I'm crediting the source of the cover image properly whenever I can next to crediting the artist.*

Playing:
![image](https://github.com/user-attachments/assets/d8695775-922e-422d-9998-764d52e4bbec)
![image](https://github.com/user-attachments/assets/305bb6a5-88ec-4a8b-a267-955e1752bccb)

Paused:
![image](https://github.com/user-attachments/assets/d2ae7b9a-c381-4b62-b5fd-50f069a27a34)
![image](https://github.com/user-attachments/assets/5dcceffa-bbad-4ad6-b5f5-0fa3c328d72c)

Paused (with the option to show how long it's paused, for those who want it):
![image](https://github.com/user-attachments/assets/33be22e4-6f96-46b6-96fd-694817497c97)

Same in Discord light mode:
![image](https://github.com/user-attachments/assets/628185ae-e5f2-47a0-b7cb-fdbd32540551)
![image](https://github.com/user-attachments/assets/4b345696-fa44-49d1-be22-e581ea2347ce)

What the icon looks like in light mode with a lighter cover image:
![image](https://github.com/user-attachments/assets/1bf0d537-9e76-488d-afd1-26a056dfbc43)
![image](https://github.com/user-attachments/assets/f8f896fa-15a9-4821-9750-f164bcb7111d)

**Comment by ungive** [comment]
Modified appearance menu, also moved the setting to hide the player logo down:

![image](https://github.com/user-attachments/assets/c9f0822c-ecb3-4040-9731-714983d0778e)

**Comment by NocFA** [comment]
That is a beautifully clean implement indeed, strictly visually speaking, it looks perfect.

I don't assume you've added in the ability to permit pausing of streaming services while retaining RPC?

This is, to clarify without modifying the small image, just purely don't remove RPC when paused, yeet the seeker, just have static element until resumed.

Very nice work good sir.

**Comment by NocFA** [comment]
Perfection, and, of course understood regarding the release staggering.
Thanks for the hard work, I've joined the Discord, and I shall be shooting a sponsor your way.

**Comment by ungive** [comment]
Fully implemented now, version 2.2.4 allows you to pause media with streaming services as well.

Thanks for the sponsor!
