### ISSUE TITLE
Add Cider for Apple Music

### ISSUE THREAD

**Issue by ungive** [ungive/discord-music-presence#43]
### Describe the problem

Add support for https://cider.sh.

For that I need app identifiers for Cider which I can't access because I have not purchased Cider. If you are a user of Cider please help by submitting your detected players (either with "Submit detected media players" or "My media player is not detected" in the help menu of Music Presence).

Missing platforms:
- [x] ~~Cider on Windows 10 (usually this ends up being just the executable filename)~~
Unfortunately Cider on Windows 10 reports as `msedgewebview2.exe`. Thanks @mercurialworld and @valery-kirichenko!
- [x] ~~Cider on Windows 11 (usually Windows 11 apps have a long and somewhat cryptic identifier)
  The version purchased via itch.io seems to only report as `msedgewebview2.exe`~~
Added! Thanks @valery-kirichenko!
- [x] ~~Cider on Mac~~
Added! Thanks @mercurialworld!

Help is greatly appreciated!

**Comment by valery-kirichenko** [comment]
Here's Cider 2.5.4_3 purchased via itch.io on Windows 11:
```
version: 2.2.5
win_winrt: msedgewebview2.exe - Microsoft Edge WebView2 (disabled)
signature: 2b33d2cf031d93a1
```

**Comment by valery-kirichenko** [comment]
Windows 10 for completeness :)
Microsoft Store:
```
version: 2.2.5
win_winrt: msedgewebview2.exe - Microsoft Edge WebView2 (disabled)
signature: 2b33d2cf031d93a1
```

itch.io:
```
version: 2.2.5
win_winrt: msedgewebview2.exe - Microsoft Edge WebView2 (disabled)
signature: 2b33d2cf031d93a1
```

(I double checked, they are identical)

**Comment by ungive** [comment]
@valery-kirichenko Thank you a lot! Now Cider can work on both Mac and Windows 11! 🚀 

Unfortunately it seems like on Windows 10 it won't be detectable. Might have to look at this again in the future, at least there is no way to tell where the media is coming from, which is an important factor in whitelisting a media player for me.

I hope you didn't buy it twice just for this! 👀

Either way, thank you for your help! Feel free to test it on Windows 11 by restarting Music Presence, it should be detected now.

**Comment by valery-kirichenko** [comment]
Regarding Windows 10, you could probably check parent process id. Not ideal but it should work if it can be implemented.
![image](https://github.com/user-attachments/assets/952a0d34-ab33-45cb-828a-cd5353f50625)

**Comment by ungive** [comment]
Good idea! I think this wouldn't be trivial though because SMTC (the API on Windows that reports currently playing media) does not provide any information about which process is reporting the media, so there's no PID available.

Here's the docs: https://learn.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssession

Only thing that comes close is the `SourceAppUserModelId` which is the executable name (not even the full path).

One might have luck iterating all processes, but with that kind of generic name (`msedgewebview2.exe`) one will certainly find multiple processes. Those could be filtered by only looking at parent processes that have a whitelisted executable name (i.e. Cider.exe), but that still doesn't 100% exclude false positives.

Tricky ^^
