### ISSUE TITLE
Opt-out setting for showing logo of media or streaming service in status

### ISSUE THREAD

**Issue by Plaged** [ungive/discord-music-presence#46]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the problem

The feature "Shows the logo of the media player or streaming service that is playing your music in your status" cannot be opt-out, being forced to have the logo of the media player next to the album cover, which can be redundant when you're already displaying the name of the player in your "Listening to ..." RPC

### Solution

A new setting, if possible, to allow users to choose whether they want to display the media player logo or not

### Additional context

It'd be perfect to mimic the Spotify look even more

**Comment by ungive** [comment]
Hey, I can definitely see the appeal in adding an option to hide the logo of the streaming service.

You can already hide the player logo of offline players, but for streaming services I didn't add such an option yet for the following reasons:

- For TIDAL I am using the [TIDAL API](https://developer.tidal.com/apiref) to get cover images (only when that cover 

https://github.com/orgs/tidal-music/discussions/57

**Comment by ungive** [comment]
Hey, I can definitely see the appeal in adding an option to hide the logo of the streaming service and I would love to just add it, but there is a few issues with that, mostly legal ones but also a technical issue.

I'd like to be very thorough in my answer to give you insight into my thinking and also provide a resource for people that want to suggest the same thing in the future (I'm sure there will be quite a few).

You can already hide the player logo of offline players, but for streaming services I didn't add such an option yet for the following reasons:

- For TIDAL I am using the [TIDAL API](https://developer.tidal.com/apiref) to get cover images and additional artists besides the main artist. By using that API I agree to their [Developer Terms of Service](https://developer.tidal.com/documentation/guidelines/guidelines-developer-terms) which requires me to show their branding next to the data I retrieved from their API. Read the quotes below for more information.
- Even if I wasn't using the TIDAL API and I didn't specifically agree to showing the service brand alongside this data, the data still indirectly comes from their platform and I want to attribute that. Music Presence is in some way a competitor to Spotify's exclusive Discord integration and status (I plan on working on a Listen Along feature soon too, which emphasises this), if Discord were to make such an integration with streaming services, they would most certainly be obligated to show their brand too. My plan is to add integrations between Music Presence and services like TIDAL some day and when that day comes, I will likely be required to show their logo wherever necessary. Which brings me to the technical reason.
- If I add this option I can't undo it, at least not without backlash from users of Music Presence. The last thing I wanna do is upset users by removing features again and I might have to at some point given the reasons above. Users would be inclined to download an old version of Music Presence or not use it at all anymore and that is something I don't want to provoke, so I'm always careful about adding features which I can't fully stand behind. I might also want to use more APIs than just the TIDAL API in the future and all of those will require me to show their brand.
- Additionally it's a moral decision too, I just wanna be on the right side of things and properly attribute the source when I can.

I hope those reasons make sense to you and showing that logo is a small price to pay for an unparalleled Discord status.

I'd love to hear your thoughts too and if that brand icon is a dealbreaker for you and for what reasons. Personally, I'm not bothered by it at all, so I'm curious about your thoughts.

Kind regards!

---

Quotes from the TIDAL Developer Terms:

> [TIDAL Developer Terms of Service](https://developer.tidal.com/documentation/guidelines/guidelines-developer-terms)
III - Use of TIDAL Marks
To the extent we make available any TIDAL logos, trademarks, or other identifiers ("TIDAL Marks") for your use in connection with Your Offering, you will use them in accordance with the TIDAL Developer Design Guidelines.

> [TIDAL Developer Design Guidelines](https://developer.tidal.com/documentation/guidelines/guidelines-design-guidelines)
Attribution
TIDAL content is owned by a variety of independent rights owners. By using TIDAL metadata (including artist, album and track names, album/artist artwork, and audio playback), you agree to always show any content alongside the TIDAL brand."

Additional resources:

- Legal question: Displaying TIDAL Content from the TIDAL Web API in a Discord status   https://github.com/orgs/tidal-music/discussions/57

---

PS:

What I also find "nice" about enforcing the brand in the status is that it's a good reminder that you are using a service and you don't "own" the music, as in, you haven't bought a copy and you're only allowed to listen to it for a limited time while paying a monthly fee. I encourage anyone to buy CDs from artists directly and listen to them with an offline media player, that's the best way to support their work. :)

But that is just my opinion and not a deciding factor.

**Comment by Plaged** [comment]
That's very interesting, thanks for sharing and being informative! I can definitely understand on how this can be an issue, personally the branding next to album cover doesn't bother me either, I was just suggesting as i thought it was an oversight, personally i'd have it disabled just to make it more similar to Spotify integration and show more of the album cover, but even the Spotify integration have a small spotify logo which is something developers currently can't do. I was thinking perhaps hiding the logo could be done if the user allows the RPC to display as Listening to Tidal instead of Listening to Music, thus at least from my understanding it would be with TIDAL's conditions. Nonetheless amazing app

**Comment by ungive** [comment]
> but even the Spotify integration have a small spotify logo which is something developers currently can't do.

Yeah, that's unfortunate, but maybe that will change in the future!

> I was thinking perhaps hiding the logo could be done if the user allows the RPC to display as Listening to Tidal instead of Listening to Music, thus at least from my understanding it would be with TIDAL's conditions.

You're right, that might be enough in TIDAL's case. If I were to use the Spotify API I'd definitely have to show the logo though (["To comply with our licensing agreements, you must always attribute content from Spotify with the logo."](https://developer.spotify.com/documentation/design)). The legal side of things is complicated and it's different with every service, I'd probably have to undo a setting like "Hide the logo when you show the player name instead of Music" in the future when I wanna use an API that requires me to show the logo/icon.

> Nonetheless amazing app

Thanks! Feel free to recommend it :)

Closing this as I'm not planning on adding an option to hide service logos anytime soon.

**Comment by antranigv** [comment]
What if I'm listening to music using Music.app, but I'm not using Apple Music streaming service? I can see a toggle that says "Show the logo of the media player", which I've toggled off, but I think that's not working for "Apple Music". again offline.

Also, thank you for being morally on the right side, and not just legally :-)

**Comment by ungive** [comment]
I'll look into this again in the future, since many streaming services don't use an external API and it's just unnecessary to show the logo then. The same goes for when the API is disabled. Feel free to subscribe to this issue for updates.

**Comment by Ascaveth** [comment]
Thanks for looking at this again!

For Apple Music, I mean cases where Music Presence reads playback info straight from the Apple Music app, especially for local files. No external API involved there, so it would be nice to hide the Apple Music logo in that case, unlike services where showing the logo is required by API terms or branding rules.

A generic "hide all logos" option sounds tricky, I get that. But just supporting this for Apple Music when the API isn't used (or is disabled) would already help a lot.

Thanks for considering it.
