### ISSUE TITLE
[Bug] Popup showing the app name missing when hovering the systray icon

### ISSUE THREAD

**Issue by hans-juergen** [ungive/discord-music-presence#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

See title, "Music Presence" is not shown when hovering its icon in the Windows 10 systray.

### Reproduction Steps

1. Go to ... Windows systray
2. Hover ... app icon
3. See the error

### Expected behavior

All other systray icons show a popup name when hovering except for Msic Presence.

### Screenshots

![image](https://github.com/user-attachments/assets/c5418ae0-ffa1-4f78-9c2c-b86baa9c1a61)

### Device Info

- Discord Music Presence version: 2.2.3
- Operating system: Windows 10 Pro
- The media player you used (if applicable): Deezer

**Comment by ungive** [comment]
Easy fix, thanks for reporting! I would've honestly never noticed it. 😄 

![image](https://github.com/user-attachments/assets/b254aa11-f81d-4828-b1b9-b8268b22c9a4)

Will be part of the next version.

**Comment by ungive** [comment]
Fixed in version 2.2.4

When media is shared in your status the tooltip text will also contain the song name and artist.

**Comment by hans-juergen** [comment]
Nice, thank you!
