### ISSUE TITLE
My media player is not detected

### ISSUE THREAD

**Issue by MidlerUnter** [ungive/discord-music-presence#51]
Players I am using, that aren't supported yet: Soundcloud
```
version: 2.2.4
win_winrt: opera.exe - Opera GX Internet Browser (disabled)
signature: 23c5066345b27485
```

---

**Comment by ungive** [comment]
Hi, browsers are currently not supported but will be in a future update.

Until then you can use the official Soundcloud app on Windows 11, that one works. The Soundcloud app on Windows 10 unforunately doesn't work, as that uses a browser too. I hope that helps until I added support for browsers!
