### ISSUE TITLE
[Bug] Cover images sometimes don't show up until re-enabling the setting or restarting Music Presence

### ISSUE THREAD

**Issue by ungive** [ungive/discord-music-presence#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The status sometimes has no image (question mark image on Discord) and that persists even when changing the song until re-enabling the feature for local cover images in the setting or restarting Music Presence.

### Reproduction Steps

Happens seemingly randomly.

### Expected behavior

It at least shows up when switching songs.

### Device Info

- Discord Music Presence version: 2.2.4
- Operating system: [e.g. Windows]
- The media player you used (if applicable): [e.g. Spotify]

**Comment by ungive** [comment]
Reason: The websocket connection of the client (Music Presence) never sends PING messages and therefore never detects some types of disconnects from the proxy server. Sending PING messages regularly and expecting timely PONG messages should fix this.

**Comment by ungive** [comment]
Side note: Sending a ping every time the Discord status is set and expecting a pong in time is a good way of detecting when the status has no image.

**Comment by Ayra19th** [comment]
How exactly does this work?

**Comment by ungive** [comment]
Here is a high-level explanation of how it works under the hood: https://github.com/ungive/discord-music-presence/blob/master/documentation/cover-images-proxy.md

For more technical details you can check here:
- Technical specification: https://github.com/ungive/loon/blob/master/api/specification.md
- Source code: https://github.com/ungive/loon

Let me know if you have any more questions!

**Comment by ungive** [comment]
The problem is caused by the client (the Music Presence app) sometimes not knowing whether it is still connected to the server. Sometimes it can happen that the connection is interrupted without it being detected, that's just the unpredictable nature of networking. In order to know whether the connection is still alive/healthy, clients send ping messages to which they expect a pong reply within a certain time period. If no pong is ever received it's pretty safe to say that the connection is interrupted, even though it might appear healthy otherwise. It's kinda like saying "hi, you still there?" on the phone multiple times a minute and hanging up when you don't get a "yeah, dude, I'm *still* here."

This is actually very common practice, to send ping/pong messages, I just didn't explicitly implement it because I was under the assumption that the websocket library I use takes care of it for me (it doesn't, for whatever reason).

Sending a ping message in regular intervals and expecting a timely pong will solve this issue. Even better will be to send an additional ping whenever the Discord status is updated, to know if the server is still there to serve the album cover. If it doesn't reply with a pong in time the client will simply reconnect and update your status again once it's connected again.

**Comment by Ayra19th** [comment]
I get it now thanks

**Comment by ungive** [comment]
Fixed and will be part of the next release.
