### ISSUE TITLE
Winamp 5.9.2 on Windows 10 Pro not detected

### ISSUE THREAD

**Issue by hans-juergen** [ungive/discord-music-presence#54]
I am playing local music files with the latest official Winamp version on my Windows 10 Pro computer, but Music Presence does not detect that Winamp is running, it only shows the Deezer desktop being active. Disabling Deezer does not change this. Is it because Winamp can also show videos perhaps and so gets blocked? I never use it for showing video files, by the way, I use the default Windows app for that.

**Comment by ungive** [comment]
Did you install Winamp using the WACUP installer? I should maybe clarify in the players documentation that vanilla Winamp does not report what it is playing to Windows.

Try running this and see if Winamp shows up: https://github.com/ungive/media-session-dump

On the releases page you can find msd.exe which dumps all media that is detected on your device. If your Winamp doesnt show up, it's not reporting anything.

**Comment by hans-juergen** [comment]
On this computer I have installed the "original" Winamp from the new owners that have released the source code in September, by the way. WACUP is installed on another computer with Windows 10 Pro as well, but there is no mixup between those two. I also read today that WACUP has its own Discord implementation and disables the existing Winamp plugin from another developer, as it causes problems.

msd.exe will show nothing when Winamp 5.9.2 is running alone, only from Deezer and Spotify while their desktop apps are paused.

**Comment by ungive** [comment]
Yeah, the "original" Winamp doesn't report any media information. WACUP should report it though! And the Winamp version that comes with WACUP should work too.

**Comment by dr0biwan** [comment]
Apologies for posting on this closed issue but thought it best to clarify something from the above. wacup currently only uses a small sub-set of the plug-ins from the 5.666 installer for its x86 build & it no longer uses the winamp core. The install step that gets the old winamp installer isn't installing winamp as I think is being assumed & is just to acquire some of the plug-ins wanted.

**Comment by ungive** [comment]
> Apologies for posting on this closed issue but thought it best to clarify something from the above. wacup currently only uses a small sub-set of the plug-ins from the 5.666 installer for its x86 build & it no longer uses the winamp core. The install step that gets the old winamp installer isn't installing winamp as I think is being assumed & is just to acquire some of the plug-ins wanted.

@dr0biwan Thanks for clarifying! I think it installed Winamp for me, when I installed it on my laptop, but I'm not sure.

Small side question, do you plan on improving the metadata that is reported to Windows by WACUP? Last time I tried the reporting was only with basic information, lacking e.g. an accurate reflection of the playback position.

**Comment by dr0biwan** [comment]
Is it just the timeline info missing for that or are there other things also needed? As I've just given it a quick try & assuming I'm providing the correct information I'm not seeing a progress bar in the discord ui.

**Comment by ungive** [comment]
![image](https://github.com/user-attachments/assets/ba700a68-7d1e-4f2b-84ef-5cbea823534b)
Output of msd.exe: https://github.com/ungive/media-session-dump

- The playback position is always 0ms (and the updated time is malformed because it's never updated)
- The end time and max seek time is also 0ms (should contain 0ms and the duration)

That info is needed for a progress bar to show in the Discord status.

I've implemented this for a foobar2000 plugin 2 days ago, if you want a reference or an implementation example: https://github.com/ungive/foo_mediacontrol/blob/master/foobar2000/foo_mediacontrol/playback_listener.cpp

Hope that helps!

**Comment by dr0biwan** [comment]
Thanks for the info though I'd already got it working per my edit (was me not doing things correctly with the winrt calls). I also hooked up reporting the genre in case that was needed. Will have a newer wacup build out with the changes later this month.

**Comment by ungive** [comment]
Great stuff! Looking forward to it

**Comment by hans-juergen** [comment]
I just installed the latest WACUP 64-bit version, was not aware that there is one before. It works with Music Presence, can wait for the missing progress bar and support for other skins than the classic look, too: 😉

![image](https://github.com/user-attachments/assets/2e1a1cd0-4916-42b9-99bc-c8751292036b)

**Comment by dr0biwan** [comment]
It's been out as a preview build for a bit over a month but has existed for a few years a beta only since it was fundamental to getting the x86 build to be able to drop the need for the winamp core a year or so back. That's good to know it also is being seen as well as scrobbling working.

**Comment by hans-juergen** [comment]
Thanks for the explanation and the link to the Winamp Skin Museum, that should be enough choices for users who want something different than the standard skin.

I will update the Last.fm support FAQ about Winamp and WACUP with the new developments:
https://support.last.fm/t/winamp-wacup-scrobbling/5645

How could old school users preferring the legacy desktop scrobbler plus its old Winamp plugin use that instead, simply by disabling the new native scrobbling option in WACUP?

@ungive: I think you can add a role for WACUP as supported media player in your server besides foobar2000 and MusicBee, or is something still missing?

**Comment by ungive** [comment]
@hans-juergen Added the roles for that

**Comment by dr0biwan** [comment]
> How could old school users preferring the legacy desktop scrobbler plus its old Winamp plugin use that instead, simply by disabling the new native scrobbling option in WACUP?
> 
My implementation is automatically disabled if the old plug-in is found whilst everything is loading. That only applies to the x86 build as the x64 build can't use the old plug-in. I also had a mode that helped to install the plug-in from the legacy lastfm installer but that was removed when I implemented my handling so manually copying the plug-in dll over is required to use it.

**Comment by ungive** [comment]
@hans-juergen I intend to do that slowly and in phases, not all at once, there's no rush for it. And I also want to work on browser, linux and scrobbling support. There's also individual reasons why I'm waiting with posting on certain subreddits:

- Discord Subreddit: I don't intend to post there until Music Presence is mature. That means scrobbling support, browser support, Linux support and a usable implementation of listening along. This would be the very last subreddit I choose to post on after I shared it on every other relevant subreddit.
- Spotify: There's an official Spotify integration already that even supports listening along, not much reason to post there atm
- TIDAL: Already posted there before and not many features were added that would benefit TIDAL users
- Apple Music: I intend to post there soon, once 2.2.5 is out which improves a few things for Apple Music users
- YouTube Music: I'll post there once browser support is here

**Comment by hans-juergen** [comment]
The Last.fm support FAQ about Winamp / WACUP is updated now, hope I did not forget important news. Also posted about this in r/last.fm and crossposted it to r/winamp and r/WACUP mentioning Music Presence as well.

@ungive: Now that you can post on Reddit again, maybe you should announce your app on some other subreddits than only r/foobar2000? I think r/discordapp would be a fitting subreddit, as they sometimes have threads about Discord RPC implementations for music, too and a large user base. Other relevant subreddits would probably be r/TIdal (no spelling mistake), r/truespotify (as r/spotify is only about playlists), r/applemusic, r/YoutubeMusic etc.
