### ISSUE TITLE
My media player is not detected

### ISSUE THREAD

**Issue by 2000Timo** [ungive/discord-music-presence#55]
Players I am using, that aren't supported yet:
```
version: 2.2.4
win_winrt: Deezer.62021768415AF_q7m17pa7q8kj0!Deezer.Music - Deezer.62021768415AF_q7m17pa7q8kj0!Deezer.Music (disabled)
signature: 635f686f508c7eb5
```

---
Windows 11, Deezer from the Microsoft Store not detected

**Comment by ungive** [comment]
Added it, thanks for reporting! You can restart Music Presence and it should be detected. Let me know if it works!

**Comment by 2000Timo** [comment]
Works, thank you for the quick response
