### ISSUE TITLE
[Bug] Chromium or "blank picture" as picture for the current music service in Discord

### ISSUE THREAD

**Issue by moeshpit** [ungive/discord-music-presence#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

MP shows the logo of Chromium or just the service's logo as current player image in Discord. Sometimes even a screenshot of the music video.

### Reproduction Steps

1. Open Spotify and go to a song that has a music video implemented (example: Ikkimel - BIKINI GRELL)
2. Click on "switch to video" on the right side
3. Open your profile on Discord and see the wrong image

### Expected behavior

Showing the correct song cover on Discord!

### Screenshots

![image](https://github.com/user-attachments/assets/afb04846-7b3e-4076-a3c1-fa874b1ee773)
I can't reproduce the Chromium logo but it was there a few times now...

### Device Info

- Discord Music Presence version: 2.2.4
- Operating system: Windows 10
- The media player you used (if applicable): Spotify

**Comment by ungive** [comment]
I don't have this feature, it may be an A/B test like someone on the Discord suggested, which might be not very stable yet. From our exchange on Discord it looks like the data you see is simply what Spotify reports, only Spotify can fix that.
