### ISSUE TITLE
[Bug] MP showing off the amount of time I paused a song even though I disabled the option

### ISSUE THREAD

**Issue by moeshpit** [ungive/discord-music-presence#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

title

### Reproduction Steps

Here is my settings file for it: [settings.json](https://github.com/user-attachments/files/17465883/settings.json)
Just pause a song and it will happen.

### Expected behavior

...not showing off the time paused.

### Screenshots

![image](https://github.com/user-attachments/assets/9cf208d8-1aba-4da7-a914-41d1c23f0575)
![image](https://github.com/user-attachments/assets/fc4607ab-72cd-4f58-b570-715f491331a6)

### Device Info

- Discord Music Presence version: 2.2.4
- Operating system: Windows 10
- The media player you used (if applicable): foobar, Spotify (maybe more?)

**Comment by ungive** [comment]
It looks like this is a Discord bug, similar to how you can't see buttons on your own profile, but others can. There's nothing I can do to prevent it from showing like that, Music Presence doesn't report any timestamps when you disable the option.
