### ISSUE TITLE
[Bug] Progress bar showing 00:00 with foobar2000

### ISSUE THREAD

**Issue by moeshpit** [ungive/discord-music-presence#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using foobar2000 and the new "freeze progress bar" option activated, the RPC shows that I'm at 00:00 of a song instead of the correct time!

### Reproduction Steps

1. Open foobar2000 and start a song
2. Listen a bit to it
3. Pause the track
4. Look at your RPC

### Expected behavior

Showing the correct progress in the RPC!

### Screenshots

![image](https://github.com/user-attachments/assets/0bcbbd81-d1fc-4108-a042-2697896b23e5)
![image](https://github.com/user-attachments/assets/8911a28d-acbb-4b67-8a6e-e2e1e2b15ae0)
The second screenshot shows that I am actually 2 minutes and 10 seconds into the song!

### Device Info

- Discord Music Presence version: 2.2.5-preview.2
- Operating system: Windows 10
- The media player you used (if applicable): foobar2000 (haven't tested it with other players as of right now...

**Comment by ungive** [comment]
The progress bar will advance with time no matter what, it can't be prevented unfortunately.

The only two options are to put it at 0:00 or at 3:32 in your case (empty progress bar or full progress bar). For this feature I've chosen to put it at 0:00, I think it looks better than 3:32 --- 3:32 and a completely white bar. If Discord adds the possibility to freeze the progress bar at a specific point in time I'll address this, but until then we're left out of options
