### ISSUE TITLE
Cider 2 not detected

### ISSUE THREAD

**Issue by mercurialworld** [ungive/discord-music-presence#68]
Players I am using, that aren't supported yet:

On MacOS:
```
version: 2.2.4
mac_mediaremote: sh.cider.electron - Cider (disabled)
signature: 1ed3589b6caaea9
```

On Windows:
```
version: 2.2.4
win_winrt: msedgewebview2.exe - Microsoft Edge WebView2 (disabled)
win_winrt: TheBrowserCompany.Arc_ttt1ap7aakyb4!Arc - TheBrowserCompany.Arc_ttt1ap7aakyb4!Arc (disabled)
signature: 4f68d7a952f6889
```

---

Currently using Cider v2.5.4 Patch 3 (stable) on both Windows 11 Pro 23H2 and MacOS Sequoia 15.0.1. Cider on MacOS seems to be running with Electron, and on Windows it seems to be using Edge WebView. 

I bought Cider via itch.io; unsure of what it would show as when bought via the Microsoft Store.

**Comment by ungive** [comment]
Thanks! Added Cider for Mac and updated #43 

Unfortunately I can't add `msedgewebview2.exe` for Cider on Windows as the identifier is too universal. Maybe The Windows Store version reports something more meaningful.

Do you have access to a Windows 10 machine and can you try the itch.io version there?

**Comment by mercurialworld** [comment]
I currently won't have access to a PC running Windows 10 until a bit into next week; as soon as I do though I'll try it out and let you know!

**Comment by ungive** [comment]
That sounds perfect, thanks! I'll close this issue, you can just comment on #43 once you have tested it or ping me in the Discord
