### ISSUE TITLE
My media player is not detected

### ISSUE THREAD

**Issue by justinespinal** [ungive/discord-music-presence#70]
Players I am using, that aren't supported yet:
```
version: 2.2.4
win_winrt: chrome.exe - Google Chrome (disabled)
signature: 53dfb61d84cb551
```

---

**Comment by justinespinal** [comment]
using iTunes but its not being detected

**Comment by ungive** [comment]
iTunes does not report media to Windows unfortunately. There seems to be a project though that might enable that: https://github.com/thewizrd/iTunes-SMTC

If you wanna give that a shot and report detected media players again after playing media with it installed, it might be detected

**Comment by hans-juergen** [comment]
I can confirm that Music Presence does not recognise iTunes 12.13.4.4 when playing local files.

It seems that the recommended external app iTunes-SMTC is not available on the MS Store anymore, as the download link on the GitHub page times out after a while, and a search does not find it.

Downloading, unzipping and starting the x64 version 1.2 on Windows 10 Pro shows this message:

![image](https://github.com/user-attachments/assets/b2325a09-5d08-408f-8831-97c4c9a34782)

Not sure if I already have the requested .NET desktop runtime in my Windows version though.

**Comment by ungive** [comment]
Installing it should probably be fine, especially if you do it through the download link, `aka.ms` is an official Microsoft domain

**Comment by hans-juergen** [comment]
OK, downloaded and  successfully installed, also started a new album in iTunes, nothing changed yet. I  guess I have to restart my PC first which normally happens when there is new .NET runtime stuff provided by the Windows Updater.

Scrobbling with the Last.fm desktop scrobbler 3.1.29.1 still works, by the way.

**Comment by ungive** [comment]
do you see media reported to Windows? either way, after restarting and running iTunes with that plugin, you could submit detected media players to see if it's detected (Help > Submit detected media players)

**Comment by hans-juergen** [comment]
The iTunes notification for a new track in the lower right corner works. I will submit a new report now, as I still get the same error message about having to install .NET runtime.

**Comment by ungive** [comment]
iTunes works with iTunes-SMTC: https://github.com/thewizrd/iTunes-SMTC

![image](https://github.com/user-attachments/assets/fe769f07-19e3-49dc-a2c0-079cb7640108)

Whitelisted it too, after restarting Music Presence and installing iTunes-SMTC it should work!
