### ISSUE TITLE
Add support for WebPs and other newer file formats

### ISSUE THREAD

**Issue by Sky7734** [ungive/discord-music-presence#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Currently on foobar2000 I have a handful of songs with a WebP album art (mostly from the YouTube Source plugin) and none of them display in my status. This is a little unfortunate as from what I can tell it's the only downgrade from foo_discord_rich + catbox.moe file host. Currently I can convert them to JPG or PNG but either at the loss of quality to retain the same file size, or drastically increase the file size. This can also be useful for more formats in the future such as AVIF.

### Solution

Add support for WebP and potentially other image formats for album arts.

### Alternatives

Potentially swap file hosts depending on how it is internally set up to one that supports more file formats.

**Comment by ungive** [comment]
Can you send an example video with which you get webp thumbnails? I only get jpeg and png and I've tried a few.

Also which version of the foobar plugin are you using?
