### ISSUE TITLE
iTunes 12.13.4.4 on Windows 10 Pro is not recognised (error message about .NET runtime missing by iTunes.SMTC.exe)

### ISSUE THREAD

**Issue by hans-juergen** [ungive/discord-music-presence#72]
I am playing an album with iTunes, and I already downloaded and installed the missing .NET runtime and restarted my PC, but I get the same error message when starting iTunes.SMTC.exe in my Download folder:

![image](https://github.com/user-attachments/assets/ae28289b-159c-46ad-9f2b-a182fda4e658)

Not sure if it should be moved to an iTunes folder perhaps.

**Comment by hans-juergen** [comment]
OK, how did you install iTunes.SMTC.exe and e_sqlite3.dll, in which folder do these two files from the Zip package reside after installation? I just found out that my iTunes folder with iTunes.exe is hidden in C:\Program Files\WindowsApps\AppleInc.iTunes_12134.4.3008.0_x64__nzyj5cx40ttqa, and for some unknown reason the .NET runtime was installed on my D: drive which hosts another Windows 10 Home version. 😖

**Comment by ungive** [comment]
I just double-clicked it and it was running, I don't think you should put it there

**Comment by hans-juergen** [comment]
So the download link to the MS Store worked for you?

**Comment by ungive** [comment]
No, I downloaded the release of itunes-smtc from the github, extracted it and double-clicked the exe
