### ISSUE TITLE
macOS menu music presence?

### ISSUE THREAD

**Issue by jbwharris** [ungive/discord-music-presence#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I currently employ a method to display my music presence essentially in macOS. This is using [1Thing](https://apps.apple.com/in/app/the-1thing/id6451387174) and [Shortery](https://apps.apple.com/us/app/shortery/id1594183810?mt=12) that runs an Apple Shortcut that queries the last.fm API every 30 seconds. 

![image](https://github.com/user-attachments/assets/f2b3fcb3-3678-496c-af3e-09d4f22059ba)

Obviously I already have this working, but I feel like what I'm using 3 different tools to do something that could totally be integrated into your app. I'd love something that showed what I'm currently playing in the menu bar, which obviously you're already doing on some level. But if nothing is playing you can query the last.fm (or libre.fm or ListenBrainz) to check if something is playing outside of the OS. That way if I'm listening to music on my phone, I can see it's scrobbling properly, even if I'm not currently listening on my computer. Or if I'm not listening to music at all, I'd still be able to see what I was last listening to, no matter the platform.

**Comment by ungive** [comment]
Hey there, glad you found Music Presence working well with your setup!

> But if nothing is playing you can query the last.fm (or libre.fm or ListenBrainz) to check if something is playing outside of the OS.

Doesn't your current setup already do that? If not, I'm sure there are other tools that can make queries like that.

> I'd love something that showed what I'm currently playing in the menu bar, which obviously you're already doing on some level.

My macOS development skills are very limited, at the moment I'm also focusing more on expanding the functionality of Music Presence, see the [roadmap](https://github.com/ungive/discord-music-presence/blob/master/documentation/roadmap.md). Maybe at some point in the future when I focus on polishing the macOS app more I can consider adding something like this. But for now I want to keep the UI/tray menu as simple as possible until Music Presence is feature-complete.

I hope that's not a disappointment! Let me know if you have any more thoughts on the matter.

**Comment by jbwharris** [comment]
> Doesn't your current setup already do that? If not, I'm sure there are other tools that can make queries like that.

Sorry if I was unclear there. My setup is functional, but also just cobbled together using a couple tools. I'd love to see your tool offer the functionality that I'm essentially using 3 pieces of software to achieve. 

And no worries if it's not a priority, I just wanted to throw the idea out there. For me, as an infrequent Discord user, that part is less important to me. The overall concept you're building of essentially a cross platform Music Presence app feels like it could be useful in more broader contexts than just Discord.

**Comment by ungive** [comment]
Thanks for the idea!

I'll likely come back to this when I'm polishing the UI. I've given this issue the "future" label so I can find it easily later, but for now I will close this issue, as it's not a priority.

Feel free to open another issue if you have any more ideas, I'm more than happy to hear them!
