### ISSUE TITLE
Add Audirvāna software

### ISSUE THREAD

**Issue by Antoine-Audirvana** [ungive/discord-music-presence#79]
Hi, I'm from [Audirvāna](https://audirvana.com/), a music playback software, and I had a request from a user to get the integration of the paying track in Discord.

It would be better to come with software like yours, which gives them the freedom to get music playing from various apps.

Could you let me know what information you need from my end?

Thanks,
Antoine
Customer Support and Partnership Manager

**Comment by ungive** [comment]
Hey Antoine, thanks for reaching out!

For a media player to work with Music Presence it needs to report what it is playing to the operating system. I'm not sure if your player does that, but there's a good chance it does if you can see the media in the native media control interface of your operating system, see here: https://imgur.com/a/YDQegwW

You'd need to follow these steps for me to add Audirvana to Music Presence and you need to repeat these steps for each operating system (Windows 10, Windows 11, macOS):
1. Download and install Music Presence for your operating system, then run it
2. Now play some media with Audirvāna, a few seconds of playback suffice
3. Click on the tray icon of Music Presence, navigate to the Help menu and click "Submit detected media players". This opens a new GitHub issue, but you can copy the contents and submit them as a comment here.

The information that's filled out in the issue allows me to whitelist the player, given that it is detected.

Looking forward to hearing back from you!

**Comment by ungive** [comment]
@Antoine-Audirvana Are you still interested in this?

Would be awesome if you or someone else with access to the application could submit the needed player identifiers!

**Comment by Antoine-Audirvana** [comment]
Hi Jonas,

I’m sorry, but I couldn’t send this to our developer because we had an urgent task to do, given that the BF is approaching.

I will talk about it with him next week.

To ensure I’m on the right path, can you confirm whether we need to add this to our code?

https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/integrate-with-systemmediatransportcontrols

https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter

Thanks,
Antoine

From: Jonas van den Berg ***@***.***>
Date: Wednesday, 27 November 2024 at 18:44
To: ungive/discord-music-presence ***@***.***>
Cc: Antoine Douaillat ***@***.***>, Mention ***@***.***>
Subject: Re: [ungive/discord-music-presence] Add Audirvāna software (Issue #79)

@Antoine-Audirvana<https://github.com/Antoine-Audirvana> Are you still interested in this?

Would be awesome if you or someone else with access to the application could submit the needed player identifiers!

**Comment by ungive** [comment]
@Antoine-Audirvana I can confirm the Windows link is correct. The Apple link looks correct too, but I can't confirm for sure. As long as your media player reports what it is playing in the media controls of the OS as a result of implementing it with that, it should be right.

**Comment by ungive** [comment]
I will close this issue for now, as it's my understanding that Audirvāna does not report currently playing media at this time. Feel free to reopen the issue once this is implemented on your side and I am happy add support for the application!
