### ISSUE TITLE
Precise Customisability

### ISSUE THREAD

**Issue by jayrickaby** [ungive/discord-music-presence#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Being given a million options for how the Rich Presence looks on Discord can be both a blessing a curse. There's lots of options to choose from, but what if there was a _specific_ way you wanted to look that wasn't actually supported?
For example, what if you wanted to customise how the "Listening to..." looked. Currently, it only supports "Music" and the Player you're using to listen to the music on. What if you wanted it to say "Listening to Pink Floyd?"

### Solution

Foobar2000 has a customisability system with tags. I'm not an experienced foobar2000 user, but I've tried customising with their tags and found it quite intuitive. Some example tags are: %artist% for the Artist name, %album% for the Album name, etc. 
Now, I'm not sure how difficult it would be to implement this, but this can help customisability tenfold. 
For example, say that the Rich Presence box was made into a customisable field for the Heading and subtext. By default it may be:
```
Heading: 
%title%

Subtext: 
by %artist%
on %album%
```
Users may be able to edit this to be whatever they want, swapping stuff around and having custom 'filler' text.

Likewise, support for the status thing would be awesome as well. Exactly the same process:
`Listening to Music`
The "Listening to" and "Playing" may be more of a drop-down selection rather than custom text field, I'm not sure if discord allows it to be that customisable.
However, you may be able to replace "Music" with %artist%, %album%, etc and it show up accurately.

### Alternatives

Presets so that users may not have to figure it about themself if they don't want to would be a nice touch :]

**Comment by ungive** [comment]
An issue for this already exists: #42 

I'm definitely planning on adding more customizability for the Discord status with a text field where you can enter whatever you like, including variables for available metadata, similar to how you can do it in foobar2000! Read the linked issue for more info. Right now I'm prioritising implementing scrobbling, but in the near future this will become an option.

Regarding "Listening to %artist%", that's not possible using Discord RPC, the name after "Listening to" is bound to the application ID that was created in the Discord Developer portal, so it can't contain any variables unfortunately. For more info see #11.

I'll be closing this, as an issue already exists, but feel free to comment on #42 if you have any more ideas or thoughts on what was already discussed there!
