### ISSUE TITLE
[Bug] Time shown in discord VERY wrong compared to actual playback time

### ISSUE THREAD

**Issue by FragileDeviations** [ungive/discord-music-presence#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The playback time shown in the presence is completely different to the real time.

### Reproduction Steps

1. Play a song in MusicBee
2. Wait a few seconds
3. See that it's the wrong time

### Expected behavior

It should show the actual time in the playback.

### Screenshots

![image](https://github.com/user-attachments/assets/4052cf57-d203-499f-ab9c-46887984967c)
![image](https://github.com/user-attachments/assets/eeeb6dcc-7409-4a36-bf05-8f19b011e6b0)

### Device Info

- Discord Music Presence version: 2.2.5
- Operating system: Windows 11
- The media player you used (if applicable): MusicBee

**Comment by ungive** [comment]
Hey, try installing the plugin for MusicBee that is mentioned here: https://github.com/ungive/discord-music-presence/blob/master/documentation%2Fsupported-media-players.md

In your case it is most likely the case that you don't have that plugin. By default, MusicBee only reports basic metadata and the playback position is not part of that, so Music Presence falls back to guessing it.

Let me know if that helps.

In rare other cases the playback position can also be off when your system time is out of sync, that just as a side note.

**Comment by FragileDeviations** [comment]
That plugin is installed, yeah.
My system time should be fine? It's set to my timezone, and it shows the exact same time as my phone and my watch.

**Comment by ungive** [comment]
Can you check it's the same plugin and it's up to date? I remember someone mentioning they had a plugin with the same name downloaded from the MusicBee website, but it was outdated. It has to be the plugin from the linked GitHub, that's the only one I know of that reports all metadata

**Comment by FragileDeviations** [comment]
That fixed it. Didn't know I had an outdated version. Thanks!
