### ISSUE TITLE
Apple Music not being detected after updating from the Microsoft Store.

### ISSUE THREAD

**Issue by WildRiley** [ungive/discord-music-presence#83]
After updating Apple Music through the Microsoft Store, Music Presence can't detect Apple Music anymore.
I restarted both apps and made sure the audio was playing, but Music Presence didn't detect that Apple Music was playing audio.

**Comment by ungive** [comment]
For me this is not an issue on Windows 10, I didn't have any updates for Apple Music and it still works after reinstalling

**Comment by ungive** [comment]
I've installed it on a Windows 11 machine and it seems to work fine there too. If you still have this issue, feel free to reopen this! You can always click "Help > Submit detected media players" if a media player is not detected, but you think it should be.
