### ISSUE TITLE
My media player is not detected

### ISSUE THREAD

**Issue by xIpswich** [ungive/discord-music-presence#87]
Players I am using, that aren't supported yet:
```
version: 2.2.6
win_winrt: 308046B0AF4A39CB - 308046B0AF4A39CB (disabled)
signature: 7f9401842da64ad5
```

---
Spotify (MS Store App) didn't, but as soon as I manually reinstalled it through the Spotify website, Spotify worked on the player.

**Comment by ungive** [comment]
Thanks! Spotify seemingly wasn't detected here unfortunately
