### ISSUE TITLE
Plexamp scrobbling

### ISSUE THREAD

**Issue by mavproductions** [ungive/discord-music-presence#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Hey!

I am kind of beginning to move away from iTunes for Windows to using [Plexamp](https://www.plex.tv/en-ca/plexamp/) as my main source of music streaming/casting/listening in my entire digital framework.

I'm wondering if you could begin to support what is becoming a very growing popular app/platform within [Plex](https://www.plex.tv/).

Thanks for reading my request! :)

Enjoy your weekend

**Comment by ungive** [comment]
Hey there :) 

Scrobbling will be added in a future update, see #53. If Plex is detected by Music Presence then, it will be possible to scrobble media from Plex as well!

Right now Plex is not supported though. Last time I tried using Plex with Music Presence I found out that it doesn't report the media it is playing to Windows. You can still give a try though by following these steps:
1. Download and install Music Presence for your operating system, then run it
2. Now play some media with any and all media players that you use to play Plex media, a few seconds of playback suffice
3. Click on the tray icon of Music Presence, navigate to the Help menu and click "Submit detected media players". This opens a new GitHub issue, you can either submit that or copy the contents and submit them as a comment here.

Music Presence will detect any media in the background, even though it might not appear in the tray menu. This step of submitting detected players is necessary so I can add it to Music Presence, I'm manually whitelisting each player.

Let me know if you have any more questions!

**Comment by ungive** [comment]
Thanks for the information! Looks like Plex only sends a notification, but doesn't report live playback information to Windows. Unfortunately Plex won't work with Music Presence then or the future scrobbling feature :/

You could reach out to their support or make a feature request with them by mentioning "SMTC" (System Media Transport Controls) which is the technology that they need to implement for this and by asking them if they can integrate with Windows media controls that are visible in these screenshots: https://imgur.com/a/YDQegwW

If at some point Plex does report media to the operating system, feel free to open a new issue!

Until then, I'll close this, as there is nothing I can do here.

Thanks for opening this issue again!

**Comment by LiMoon** [comment]
> Plexamp shows a notification in Windows notification center from it's own app, but doesn't integrate into Microsoft's Windows Media Player "listener" or anything like that, to distinguish itself as a recognized media player.
> 
> ![image](https://github.com/user-attachments/assets/a395d402-d6b2-4aff-8af4-bdee132aa97b)

Votes are welcome for the proposed feature... https://forums.plex.tv/t/plexamp-windows-support-windows-smtc/911833
