### ISSUE TITLE
Plexamp

### ISSUE THREAD

**Issue by fijibestwater** [ungive/discord-music-presence#96]
### Describe the problem

The media player I use Plexamp doesn't work with this app :(

**Comment by ungive** [comment]
Please see #94 and my latest comment on it.

Plexamp does not report what media it is playing to Windows, which is a problem with Plexamp itself. I encourage you to open a feature request with their media player! You can quote this from me if you like:

> For Plexamp to be detected by Music Presence, Plexamp needs to report what media it is playing to the operating system. On Windows this would e.g. be done via SMTC (System Media Transport Controls), which is the Windows API that pretty much every media player or application uses to offer playback information and media controls to the user through Windows's native controls: https://imgur.com/a/YDQegwW Implementing this would not only make Plexamp work with Music Presence, but also offer every Plexamp user a better user experience, which ultimately makes Plexamp a better media player. Plexamp should report at least this information to work flawlessly with Music Presence: Playback status (playing or paused), song title, artist, album name, live playback position, song duration and the album cover image. Official Windows Documentation for SMTC: https://learn.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols

Once Plexamp supports this, feel free to open a new issue!

Perhaps also let me and others know if you made a feature request with their media player :)

**Comment by ungive** [comment]
I've added a generic template to the documentation: https://github.com/ungive/discord-music-presence/blob/master/documentation/support-template.md

It's also reference it in the troubleshooting guide: https://github.com/ungive/discord-music-presence/blob/master/documentation/troubleshooting.md
