### ISSUE TITLE
Spotify not well recognized on Arch Linux

### ISSUE THREAD

**Issue by VZCE** [ungive/discord-music-presence#97]
The player is well supported; however, he is not well recognized. As a result, on the Discord profile, "Music" is displayed instead of "Spotify".

Tested on Arch Linux (GNOME 47.2)
Spotify client installed via Pacman

```
version: 2.2.7
lin_mpris: spotify - spotify (enabled)
signature: e452cc89b196f041
```

---

**Comment by ungive** [comment]
Added, thanks!
